.Dd 2020-06-07
.Dt EWMH 1
.Os POSIX.1
.Sh NAME
.Nm ewmh
.Nd EWMH compliance daemon
.Sh SYNOPSIS
.Nm ewmh
.Op Fl h
.Sh DESCRIPTION
.Nm
is a user-space daemon that listens for X notify events, and respond to
them by setting Extended Window Manager Hints on the root window, as specified by
the specification.
.Pp
Some applications require an EWMH compliant window manager in order to
function properly. Many window managers, however do not comply to the
specification, which end up with unexpected behavior for these
applications, when they even start at all.
.Pp
.Nm
aims to provide a sane amount of hints, so that most
applications can function properly with a non EWMH compliant window
manager.
.Sh IMPLEMENTATION NOTES
.Ss _NET_SUPPORTED
The whole specification cannot be fully implemented in an external tool,
for multiple reasons (need to redirect root window events, keep track
of window states, …).
.Pp
Only the following atoms are supported by
.Nm :
.Pp
.Bl -bullet -compact
.It
_NET_SUPPORTED
.It
_NET_SUPPORTING_WM_CHECK
.It
_NET_WM_STATE
.It
_NET_WM_STATE_FULLSCREEN
.It
_NET_CLIENT_LIST
.It
_NET_CLIENT_LIST_STACKING
.It
_NET_ACTIVE_WINDOW
.It
_NET_WM_WINDOW_TYPE (all types)
.El
.Ss _NET_SUPPORTING_WM_CHECK
The specification require that a running window manager creates a window
and point the hint to this window.
.Nm
will set the override_redirect property on this window so that non-EWMH
compliant window manager will ignore it as well.
.Ss _NET_WM_STATE
The only supported state in _NET_WM_STATE_FULLSCREEN. When such event
is sent to the root window,
.Nm
will respond to the event accordingly. When setting a window fullscreen,
its current position, size and border width are saved in an atom named
ORIGINAL_SIZE.
.Nm
needs this atom to revert the window back to its original state.
.Ss _NET_CLIENT_LIST
.Ss _NET_CLIENT_LIST_STACKING
These atoms hold the list of windows that are managed by the window manager
(override_redirect unset), and/or have the hint _NET_WM_WINDOW_TYPE set to one of those values
.Pp
.Bl -bullet -compact
.It
_NET_WM_WINDOW_TYPE_UTILITY
.It
_NET_WM_WINDOW_TYPE_DIALOG
.It
_NET_WM_WINDOW_TYPE_NORMAL
.El
.Pp
Because we don't know the order in which the running window manager is
storing the windows, _NET_CLIENT_LIST also displays the window IDs in
their stacking order.
.Pp
All other windows will have their
.Em override_redirect
attribute forcely set to 1, so that window managers without support for
EWMH atoms can ignore them.
.Ss _NET_ACTIVE_WINDOW
This hint is updated whenever an event of type
.Em FOCUS_IN
is generated. This should usually match the currently active window from
the window manager point of view.
.Sh SEE ALSO
.Xr glazier 1
.Sh AUTHORS
.An Willy Goiffon Aq Mt dev@z3bra.org
